# Generated by Django 6.0.7 on 2026-08-03 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='recording_available',
            new_name='study_materials',
        ),
    ]
